name: Build Ansible Collection

on:
  push:
    tags:
      - '*'

jobs:
  build-latest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Get the version
        id: get_version
        run: echo $GITHUB_REF - ${GITHUB_REF/refs\/tags\//}
      
      - name: check tag version
        run: echo $TAG_VERSION

      - name: update repos
        run: sudo apt update -y

      - name: install build deps
        run: sudo apt install python3-virtualenv make tree -y

      - run: ls -R

      - name: "add version to galaxy colection"
        run: sed -i -e "s/{{ TAG-VERSION }}/$TAG_VERSION/g" ./ansible-plugin/ws/galaxy.yml

      - name: "check galaxy colection"
        run: cat ansible-plugin/ws/galaxy.yml

      - name: "create virtualenv"
        run: make venv

      - name: "build galaxy omprog"
        run: make build

      - name: "publish galaxy omprog"
        run: make publish token=$TOKEN_GALAXY

env:
  TOKEN_GALAXY: ${{ secrets.TOKEN_GALAXY }}
  TAG_VERSION: ${{ GITHUB_REF/refs\/tags\// }}

